#!/usr/bin/env node

/**
 * Development Setup Script
 * Creates .env.local file with development configuration
 */

const fs = require("fs");
const path = require("path");

const envContent = `# Development Environment Configuration
# This file is automatically generated for development

# Database (SQLite for local development)
DATABASE_URL="file:./dev.db"

# NextAuth Configuration
NEXTAUTH_URL="http://localhost:3000"
NEXTAUTH_SECRET="development-secret-key-change-in-production"

# Admin Configuration
ADMIN_EMAIL="admin@example.com"

# Vercel Blob Storage (optional)
# BLOB_READ_WRITE_TOKEN="your-vercel-blob-token"

# Production deployment notes:
# When deploying to Vercel, set these environment variables in Vercel dashboard:
# - DATABASE_URL=your-vercel-postgres-connection-string
# - DIRECT_URL=your-vercel-postgres-direct-connection-string
# - NEXTAUTH_URL=https://your-domain.vercel.app
# - NEXTAUTH_SECRET=secure-random-string-generate-with-openssl
# - ADMIN_EMAIL=your-admin-email@domain.com
`;

const envPath = path.join(process.cwd(), ".env.local");

if (!fs.existsSync(envPath)) {
  fs.writeFileSync(envPath, envContent);
  console.log("✅ .env.local file created successfully!");
  console.log(
    "📝 Please review and update the environment variables as needed."
  );
} else {
  console.log("⚠️ .env.local already exists. Skipping...");
}
